vich_uploader:
    db_driver: orm

    mappings:
        projects:
            uri_prefix: /images/projects
            upload_destination: '%kernel.project_dir%/public/images/projects'
        blog:
            uri_prefix: /images/blog
            upload_destination: '%kernel.project_dir%/public/images/blog'
        clients:
            uri_prefix: /images/clients
            upload_destination: '%kernel.project_dir%/public/images/clients'
